DISTRICTS_NAME = [
    "pn",
    "ds",
    "nc",
    "br",
    "bk",
    "bkp",
    "ptw",
    "ppstp",
    "pkn",
    "mbr",
    "lkb",
    "ynw",
    "sptw",
    "pyt",
    "tbr",
    "bky",
    "hk",
    "ks",
    "tlc",
    "bkn",
    "bkt",
    "pscr",
    "nk",
    "rbrn",
    "bp",
    "dd",
    "bku",
    "st",
    "bs",
    "ctc",
    "bkl",
    "pw",
    "kt",
    "sl",
    "ct",
    "dm",
    "rctw",
    "lp",
    "wtn",
    "bkh",
    "ls",
    "sm",
    "kny",
    "sps",
    "wtl",
    "ksw",
    "bn",
    "twwtn",
    "tk",
    "bb"
]

DISTRICTS_CODE = {
    "All": 0,
    "Bang Bon": 50,
    "Bang Kapi": 6,
    "Bang Khae": 40,
    "Bang Khen": 5,
    "Bang Kho Laem": 31,
    "Bang Khun Thian": 21,
    "Bang Khun Thain": 21,
    "Bang Na": 47,
    "Bang Phlat": 25,
    "Bang Rak": 4,
    "Bang Sue": 29,
    "Bangkok Noi": 20,
    "Bangkok Yai": 16,
    "Bueng Kum": 27,
    "Chatuchak": 30,
    "Chom Thong": 35,
    "Din Daeng": 26,
    "Don Mueang": 36,
    "Dusit": 2,
    "Huai Khwang": 17,
    "Khan Na Yao": 43,
    "Khlong Sam Wa": 46,
    "Khlong San": 18,
    "Khlong Toei": 33,
    "Lak Si": 41,
    "Lat Krabang": 11,
    "Lat Phrao": 38,
    "Min Buri": 10,
    "Nong Chok": 3,
    "Nong Khaem": 23,
    "Pathum Wan": 7,
    "Phasi Charoen": 22,
    "Phaya Thai": 14,
    "Phra Khanong": 9,
    "Phra Nakhon": 1,
    "Pom Prap Sattru Phai": 8,
    "Prawet": 32,
    "Rat Burana": 24,
    "Ratchathewi": 37,
    "Sai Mai": 42,
    "Samphanthawong": 13,
    "Saphan Sung": 44,
    "Sathon": 28,
    "Suan Luang": 34,
    "Taling Chan": 19,
    "Thawi Watthana": 48,
    "Thon Buri": 15,
    "Thung Khru": 49,
    "Wang Thonglang": 45,
    "Wang Thong Lang": 45,
    "Watthana": 39,
    "Yan Nawa": 12
}

DISTRICTS = [
"Phra Nakhon",
"Dusit",
"Nong Chok",
"Bang Rak",
"Bang Khen",
"Bang Kapi",
"Pathum Wan",
"Pom Prap Sattru Phai",
"Phra Khanong",
"Min Buri",
"Lat Krabang",
"Yan Nawa",
"Samphanthawong",
"Phaya Thai",
"Thon Buri",
"Bangkok Yai",
"Huai Khwang",
"Khlong San",
"Taling Chan",
"Bangkok Noi",
"Bang Khun Thian",
"Phasi Charoen",
"Nong Khaem",
"Rat Burana",
"Bang Phlat",
"Din Daeng",
"Bueng Kum",
"Sathon",
"Bang Sue",
"Chatuchak",
"Bang Kho Laem",
"Prawet",
"Khlong Toei",
"Suan Luang",
"Chom Thong",
"Don Mueang",
"Ratchathewi",
"Lat Phrao",
"Watthana",
"Bang Khae",
"Lak Si",
"Sai Mai",
"Khan Na Yao",
"Saphan Sung",
"Wang Thonglang",
"Khlong Sam Wa",
"Bang Na",
"Thawi Watthana",
"Thung Khru",
"Bang Bon"
]
